controller_manager:
  ros__parameters:
    update_rate: 500  # Hz For Gazebo

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    left_cartesian_compliance_controller:
      type: cartesian_compliance_controller/CartesianComplianceController
    
    right_cartesian_compliance_controller:
      type: cartesian_compliance_controller/CartesianComplianceController

left_cartesian_compliance_controller:
  ros__parameters:
    ik_solver: "forward_dynamics"
    end_effector_link: "left_tool0"
    robot_base_link: "robot_base_link"
    ft_sensor_ref_link: "left_tool0"
    compliance_ref_link: "left_tool0"
    force_enable: false
    gravity_compensation: false
    force_state_pub: false
    emergency_stop_threshold: 200.0
    joints:
      - left_shoulder_pan_joint
      - left_shoulder_lift_joint
      - left_elbow_joint
      - left_wrist_1_joint
      - left_wrist_2_joint
      - left_wrist_3_joint

    # Choose: position or velocity.
    command_interfaces:
      - position
        #- velocity

    stiffness:  # w.r.t. compliance_ref_link
        trans_x: 500.0
        trans_y: 500.0
        trans_z: 500.0
        rot_x: 100.0
        rot_y: 100.0
        rot_z: 100.0
    
    damping:
        trans_x: 1.0
        trans_y: 1.0
        trans_z: 1.0
        rot_x: 0.0
        rot_y: 0.0
        rot_z: 0.0

    solver:
        forward_dynamics:
          link_mass: 100.0
        error_scale: 0.5
        iterations: 1
        publish_state_feedback: true

    pd_gains:
        trans_x: {p: 0.1, d: 0.005}
        trans_y: {p: 0.1, d: 0.005}
        trans_z: {p: 0.1, d: 0.005}
        rot_x: {p: 0.5, d: 0.0001}
        rot_y: {p: 0.5, d: 0.0001}
        rot_z: {p: 0.5, d: 0.0001}

right_cartesian_compliance_controller:
  ros__parameters:
    ik_solver: "forward_dynamics"        
    end_effector_link: "right_tool0"
    robot_base_link: "robot_base_link"
    ft_sensor_ref_link: "right_tool0"
    compliance_ref_link: "right_tool0"
    force_enable: false
    gravity_compensation: false
    force_state_pub: false
    emergency_stop_threshold: 200.0
    joints:
      - right_shoulder_pan_joint
      - right_shoulder_lift_joint
      - right_elbow_joint
      - right_wrist_1_joint
      - right_wrist_2_joint
      - right_wrist_3_joint

    # Choose: position or velocity.
    command_interfaces:
      - position
        #- velocity

    stiffness:  # w.r.t. compliance_ref_link
        trans_x: 500.0
        trans_y: 500.0
        trans_z: 500.0
        rot_x: 100.0
        rot_y: 100.0
        rot_z: 100.0
    
    damping:
        trans_x: 1.0
        trans_y: 1.0
        trans_z: 1.0
        rot_x: 0.0
        rot_y: 0.0
        rot_z: 0.0

    solver:
        forward_dynamics:
          link_mass: 100.0
        error_scale: 0.5
        iterations: 1
        publish_state_feedback: true

    pd_gains:
        trans_x: {p: 0.1, d: 0.005}
        trans_y: {p: 0.1, d: 0.005}
        trans_z: {p: 0.1, d: 0.005}
        rot_x: {p: 0.5, d: 0.0001}
        rot_y: {p: 0.5, d: 0.0001}
        rot_z: {p: 0.5, d: 0.0001}
